### ISSUE TITLE
Проблема со скачиванием библиотеки

### ISSUE THREAD

**Issue by artemkavsk** [VladBolotov/pymurapi#2]
При попытке импортировать библиотеку в pycharm вылезает ошибка, что не распознало библиотеку. Захожу в настройки в pip и там ввожу название pymurapi. Тоже не сработало. Через консоль выдало, что не знает модуль pymurapi. Как скачать вашу библиотеку, чтобы она в pycharm считывалась?

**Comment by emily0undrgrnd** [comment]
Перед тем как импортировать библиотеку необходимо установить pymurapi из git-репозитория с помощью следующей команды:
`pip3 install git+https://github.com/murproject/pymurapi.git`
